
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

module FinancialApp {

    export class ControllerInitializer {

        public static registerControllers($app : ng.IModule) : void {
                    $app.controller('ArchiveController', ArchiveController);
                    $app.controller('AuthLoginController', AuthLoginController);
                    $app.controller('AuthLogOffController', AuthLogOffController);
                    $app.controller('CategoryCreateController', CategoryCreateController);
                    $app.controller('CategoryEditController', CategoryEditController);
                    $app.controller('CategoryListController', CategoryListController);
                    $app.controller('DefaultController', DefaultController);
                    $app.controller('ImpersonateController', ImpersonateController);
                    $app.controller('MasterController', MasterController);
                    $app.controller('MenuController', MenuController);
                    $app.controller('RecurringSheetEntryCreateController', RecurringSheetEntryCreateController);
                    $app.controller('RecurringSheetEntryEditController', RecurringSheetEntryEditController);
                    $app.controller('RecurringSheetEntryListController', RecurringSheetEntryListController);
                    $app.controller('ReportController', ReportController);
                    $app.controller('SheetController', SheetController);
                    $app.controller('SheetEntryCreateController', SheetEntryCreateController);
                    $app.controller('SheetEntryEditController', SheetEntryEditController);
                    $app.controller('SheetStatsController', SheetStatsController);
                    $app.controller('UserCreateController', UserCreateController);
                    $app.controller('UserEditController', UserEditController);
                    $app.controller('UserListController', UserListController);
            }

        public static registerControllerRoutes($routeProvider : ng.route.IRouteProvider) : void {
                $routeProvider.when('/archive', 
                {
                    controller: 'ArchiveController',
                    templateUrl: '/Angular/Archive.html'
                });
                $routeProvider.when('/auth/login', 
                {
                    controller: 'AuthLoginController',
                    templateUrl: '/Angular/AuthLogin.html'
                });
                $routeProvider.when('/auth/logoff', 
                {
                    controller: 'AuthLogOffController',
                    templateUrl: '/Angular/AuthLogOff.html'
                });
                $routeProvider.when('/manage/category/add', 
                {
                    controller: 'CategoryCreateController',
                    templateUrl: '/Angular/CategoryEdit.html'
                });
                $routeProvider.when('/manage/category/edit/:id', 
                {
                    controller: 'CategoryEditController',
                    templateUrl: '/Angular/CategoryEdit.html'
                });
                $routeProvider.when('/manage/category', 
                {
                    controller: 'CategoryListController',
                    templateUrl: '/Angular/CategoryList.html'
                });
                $routeProvider.when('/', 
                {
                    controller: 'DefaultController',
                    templateUrl: '/Angular/Default.html'
                });
                $routeProvider.when('/manage/impersonate', 
                {
                    controller: 'ImpersonateController',
                    templateUrl: '/Angular/Impersonate.html'
                });
                $routeProvider.when('/manage/entry-template/add', 
                {
                    controller: 'RecurringSheetEntryCreateController',
                    templateUrl: '/Angular/RecurringSheetEntryEdit.html'
                });
                $routeProvider.when('/manage/entry-template/edit/:id', 
                {
                    controller: 'RecurringSheetEntryEditController',
                    templateUrl: '/Angular/RecurringSheetEntryEdit.html'
                });
                $routeProvider.when('/manage/entry-template', 
                {
                    controller: 'RecurringSheetEntryListController',
                    templateUrl: '/Angular/RecurringSheetEntryList.html'
                });
                $routeProvider.when('/report', 
                {
                    controller: 'ReportController',
                    templateUrl: '/Angular/Report.html'
                });
                $routeProvider.when('/sheet/:year/:month', 
                {
                    controller: 'SheetController',
                    templateUrl: '/Angular/Sheet.html'
                });
                $routeProvider.when('/sheet/:year/:month/entries/add', 
                {
                    controller: 'SheetEntryCreateController',
                    templateUrl: '/Angular/SheetEntryEdit.html'
                });
                $routeProvider.when('/sheet/:year/:month/entries/:id', 
                {
                    controller: 'SheetEntryEditController',
                    templateUrl: '/Angular/SheetEntryEdit.html'
                });
                $routeProvider.when('/sheet/:year/:month/stats', 
                {
                    controller: 'SheetStatsController',
                    templateUrl: '/Angular/SheetStats.html'
                });
                $routeProvider.when('/manage/user/add', 
                {
                    controller: 'UserCreateController',
                    templateUrl: '/Angular/UserEdit.html'
                });
                $routeProvider.when('/manage/user/edit/:id', 
                {
                    controller: 'UserEditController',
                    templateUrl: '/Angular/UserEdit.html'
                });
                $routeProvider.when('/manage/user', 
                {
                    controller: 'UserListController',
                    templateUrl: '/Angular/UserList.html'
                });
            }
    };

}


