


// <autogenerated>
//   This file was generated using DTO.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>


module FinancialApp.DTO {

        
    export interface ISheetListing {
        
            month : number;

        
            year : number;

        
            name : string;

            }

        
    export interface ICategoryListing {
        
            id : number;

        
            name : string;

        
            description : string;

        
            canBeDeleted : boolean;

            }

        
    export interface ICategory {
        
            id : number;

        
            name : string;

        
            description : string;

            }

    }

