


// <autogenerated>
//   This file was generated using DTO.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>


declare module FinancialApp.DTO {

    export interface IObject {
        // just an empty interface which makes programming the *.tt easier
    }

        
    export interface ISheetCategoryStatistics extends IObject {
        
            categoryName : string;

        
            delta : number;

            }

        
    export interface ISheetGlobalStatistics extends IObject {
        
            totalExpenses : number;

        
            totalSavings : number;

        
            totalIncome : number;

        
            sheetSubject : any;

        
            categoryStatistics : ISheetCategoryStatistics[];

            }

        
    export interface ICalculationOptions extends IObject {
        
            savingsAccountOffset : any;

        
            bankAccountOffset : any;

            }

        
    export interface ICategory extends IObject {
        
            id : number;

        
            name : string;

        
            description : string;

            }

        
    export interface ISheet extends IObject {
        
            id : number;

        
            subject : any;

        
            name : string;

        
            updateTimestamp : any;

        
            createTimestamp : any;

        
            entries : ISheetEntry[];

        
            offset : ICalculationOptions;

            }

        
    export interface IAuthenticationInfo extends IObject {
        
            isAuthenticated : boolean;

        
            userId : number;

        
            userName : string;

            }

        
    export interface ISheetEntry extends IObject {
        
            id : number;

        
            categoryId : number;

        
            delta : number;

        
            source : string;

        
            remark : string;

        
            sortOrder : number;

        
            updateTimestamp : any;

        
            createTimestamp : any;

        
            account : AccountType;

            }

        
    export interface IInsertId extends IObject {
        
            id : number;

            }

        
    export interface IAppUserMutate extends IAppUserListing {
        
            newPassword : string;

        
            currentPassword : string;

            }

        
    export interface IAppUserListing extends IObject {
        
            email : string;

        
            userName : string;

        
            id : number;

            }

        
    export interface ILoginModel extends IObject {
        
            userName : string;

        
            password : string;

        
            persistent : boolean;

            }

        
    export interface ISheetListing extends IObject {
        
            month : number;

        
            year : number;

        
            name : string;

        
            updateTimestamp : any;

        
            createTimestamp : any;

            }

        
    export interface ICategoryListing extends IObject {
        
            id : number;

        
            name : string;

        
            description : string;

        
            canBeDeleted : boolean;

            }

    }


