


// <autogenerated>
//   This file was generated using DTO.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>


declare module FinancialApp.DTO {

        
    export interface ICategory {
        
            id : number;

        
            name : string;

        
            description : string;

            }

        
    export interface ISheet {
        
            id : number;

        
            subject : any;

        
            name : string;

        
            updateTimestamp : any;

        
            createTimestamp : any;

        
            entries : ISheetEntry[];

            }

        
    export interface IAuthenticationInfo {
        
            isAuthenticated : boolean;

        
            userId : number;

        
            userName : string;

            }

        
    export interface ISheetEntry {
        
            id : number;

        
            categoryId : number;

        
            delta : any;

        
            source : string;

        
            remark : string;

        
            updateTimestamp : any;

        
            createTimestamp : any;

        
            account : any;

            }

        
    export interface ILoginModel {
        
            userName : string;

        
            password : string;

        
            persistent : boolean;

            }

        
    export interface ISheetListing {
        
            month : number;

        
            year : number;

        
            name : string;

        
            updateTimestamp : any;

        
            createTimestamp : any;

            }

        
    export interface ICategoryListing {
        
            id : number;

        
            name : string;

        
            description : string;

        
            canBeDeleted : boolean;

            }

    }

