


// <autogenerated>
//   This file was generated using DTOEnum.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>


module FinancialApp.DTO {



    
    export enum AccountType {
        
            Invalid  = 0,

        
            BankAccount ,

        
            SavingsAccount ,

            }

    }

