language: csharp
node_js:
  - "lts/*"
mono:
  - latest
dotnet: 2.1.300
cache:
  yarn: true
  directories:
    - /home/travis/.nuget/packages/
install:
  - ./build.sh --target restore-nuget-packages
  - ./build.sh --target restore-node-packages
script:
  - ./build.sh --target test