language: csharp
node_js:
  - "node"
  - "lts/*"
mono:
  - latest
group: edge
dotnet: 2.1.300
cache:
  yarn: true
  directories:
    - /home/travis/.nuget/packages/
before_install:
  - nvm install --lts
  - nvm use --lts
  - sudo apt-get remove yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends yarn
  - yarn --version
install:
  - ./build.sh --target restore-nuget-packages
  - ./build.sh --target restore-node-packages
script:
  - ./build.sh --target test
