#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SYSTEMD_MANIFEST=/etc/systemd/system/financial-app.service
cd $DIR

echo Financial-app multi-purpose launch script

function run {
	echo Set environment variables from launch.conf
	source ./launch.conf
	
	echo Starting application
	cd app
	./App
	
	exit $?
}

function install {
	echo "Installing as systemd service"
	
	if [ -z "$1" ]; then
		echo "Error: User not given."
		echo "Usage: install [user]"
		exit -1
	fi
	
	if [ -f $SYSTEMD_MANIFEST ]; then
		echo "Error: Systemd service exists at $SYSTEMD_MANIFEST"
		exit -2
	fi
	
	echo "... Writing service manifest"
	cat > $SYSTEMD_MANIFEST <<EOF
[Unit]
Description=Financial App

[Service]
WorkingDirectory=$DIR
ExecStart=$DIR/launch run
Restart=always

# Restart service after 10 seconds if service crashes
RestartSec=10
SyslogIdentifier=financial-app
User=$1

[Install]
WantedBy=multi-user.target
EOF

	echo "... Enabling service"
	systemctl enable financial-app.service
	EXIT_CODE=$?
	
	if [ $EXIT_CODE -ne 0 ]; then
		echo "Error enable systemd service at $SYSTEMD_MANIFEST"
		rm $SYSTEMD_MANIFEST
		exit $EXIT_CODE
	fi
	
	echo "... Ensuring execution permissions"
	chmod +x ./app/App
}

function uninstall {
	if [! -f $SYSTEMD_MANIFEST ]; then
		echo "Service not installed ($SYSTEMD_MANIFEST not present)"
		exit 0
	fi

	echo "Uninstalling from systemd"
	echo "... Stopping if we're running"
	systemctl stop financial-app.service
	
	echo "... Disabling service"
	systemctl disable financial-app.service
	
	echo "... Deleting service manifest"
	rm /etc/systemd/system/financial-app.service
}

function start-service {
	echo "Starting financial-app via systemd"
	systemctl start financial-app.service
	
	EXIT_CODE=$?
	if [ $EXIT_CODE -ne 0 ]; then
		exit $EXIT_CODE
	fi
	
	echo "... Status:"
	systemctl status financial-app.service
	
	EXIT_CODE=$?
	if [ $EXIT_CODE -ne 0 ]; then
		exit $EXIT_CODE
	fi
}

function stop-service {
	echo "Stopping financial-app via systemd"
	systemctl stop financial-app.service
	
	EXIT_CODE=$?
	if [ $EXIT_CODE -ne 0 ]; then
		exit $EXIT_CODE
	fi
	
	echo "... Status:"
	systemctl status financial-app.service
}

case "$1" in
	"run")
		run
		exit $?
		;;
		
	"start")
		start-service
		exit $?
		;;
	
	"stop")
		stop-service
		exit $?
		;;
		
	"restart")
		stop-service
		start-service
		exit $?
		;;
		
	"status")
		systemctl status financial-app.service
		exit $?
		;;
		
	"log")
		journalctl -fu kestrel-hellomvc.service
		exit $?
		;;
	
	"install")
		install $2
		exit 0
		;;
	
	"uninstall")
		uninstall
		exit 0
		;;
	
	*)
		echo "Unknown option $1"
		echo ""
		echo "Options:"
		echo "  install [user]  - Install as systemd service, run as specified user"
		echo "  uninstall       - Uninstall, installed as systemd service"
		echo "  "
		echo "  restart         - Restart (if installed as systemd service)"
		echo "  start           - Start (if installed as systemd service)"
		echo "  stop            - Stop (if installed as systemd service)"
		echo "  "
		echo "  log             - View journalctl"
		echo "  status          - View systemd status"
		echo "  "
		echo "  run             - Run"
		exit -1
		;;
esac