





    



// <autogenerated>
//   This file was generated using DTOEnum.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>



module FinancialApp.DTO {

    
    /** 
* App.Models.Domain.AccountType
*/

    export enum AccountType {
                    /** 
* App.Models.Domain.AccountType.Invalid
*/

            Invalid  = 0,

                    /** 
* App.Models.Domain.AccountType.BankAccount
*/

            BankAccount ,

                    /** 
* App.Models.Domain.AccountType.SavingsAccount
*/

            SavingsAccount ,

            }

    }


